In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8098, 9751, 8429, 1772],
 [8098, 9751, 8429, 203],
 [8098, 6727, 8429, 1609],
 [7505, 6962, 7910, 5585, 82],
 [7505, 6962, 7910, 5585, 2159],
 [9599, 8098, 6377, 8429, 2206],
 [4890, 7262, 6278, 5585]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8098 9751 8429 1772]
 [   0    0    0    0 8098 9751 8429  203]
 [   0    0    0    0 8098 6727 8429 1609]
 [   0    0    0 7505 6962 7910 5585   82]
 [   0    0    0 7505 6962 7910 5585 2159]
 [   0    0    0 9599 8098 6377 8429 2206]
 [   0    0    0    0 4890 7262 6278 5585]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Prakash\Downloads\simple_rnn_imdb\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 688ms/step


array([[[ 0.00524812, -0.00388388, -0.00236871, -0.00723382,
          0.01978761,  0.04590472, -0.03758382,  0.00496756,
         -0.00474316,  0.00161661],
        [ 0.00524812, -0.00388388, -0.00236871, -0.00723382,
          0.01978761,  0.04590472, -0.03758382,  0.00496756,
         -0.00474316,  0.00161661],
        [ 0.00524812, -0.00388388, -0.00236871, -0.00723382,
          0.01978761,  0.04590472, -0.03758382,  0.00496756,
         -0.00474316,  0.00161661],
        [ 0.00524812, -0.00388388, -0.00236871, -0.00723382,
          0.01978761,  0.04590472, -0.03758382,  0.00496756,
         -0.00474316,  0.00161661],
        [-0.02072763,  0.04631324, -0.02155854, -0.03270165,
          0.03840262, -0.02819878,  0.04845133, -0.03184377,
         -0.03377098,  0.01786019],
        [-0.0219672 , -0.02593516,  0.02989939, -0.04336243,
         -0.04264176, -0.01614311,  0.02741391, -0.04238399,
          0.01520412,  0.02300936],
        [-0.005678  ,  0.02630639, -0.00095823,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 8098, 9751, 8429, 1772], dtype=int32)

In [18]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 335ms/step


array([[[ 0.00524812, -0.00388388, -0.00236871, -0.00723382,
          0.01978761,  0.04590472, -0.03758382,  0.00496756,
         -0.00474316,  0.00161661],
        [ 0.00524812, -0.00388388, -0.00236871, -0.00723382,
          0.01978761,  0.04590472, -0.03758382,  0.00496756,
         -0.00474316,  0.00161661],
        [ 0.00524812, -0.00388388, -0.00236871, -0.00723382,
          0.01978761,  0.04590472, -0.03758382,  0.00496756,
         -0.00474316,  0.00161661],
        [ 0.00524812, -0.00388388, -0.00236871, -0.00723382,
          0.01978761,  0.04590472, -0.03758382,  0.00496756,
         -0.00474316,  0.00161661],
        [-0.02072763,  0.04631324, -0.02155854, -0.03270165,
          0.03840262, -0.02819878,  0.04845133, -0.03184377,
         -0.03377098,  0.01786019],
        [-0.0219672 , -0.02593516,  0.02989939, -0.04336243,
         -0.04264176, -0.01614311,  0.02741391, -0.04238399,
          0.01520412,  0.02300936],
        [-0.005678  ,  0.02630639, -0.00095823,  0.0